### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by torch2424** [dannye/waveform-gb#1]
Hello! Was wondering if you were planning on adding a license for this repo? 

I run an open source GB emulator called [wasmBoy](https://github.com/torch2424/wasmBoy), and its sister project [vaporBoy](https://github.com/torch2424/vaporBoy), and I am always looking out for cool open source ROMs to include on the project for testing, and playing with by users.

Would be awesome if I could add this. No worries if not. Thanks! 😄

**Comment by dannye** [comment]
Sure thing! If you used this for testing and/or shared it with others that'd be super cool.

**Comment by torch2424** [comment]
@dannye Oh awesome! Thank you very much! Opened an issue on my repo as well if you are interested 😄 https://github.com/torch2424/wasmBoy/issues/232
